name:		"6677ba's Notes"
description:	"tech notes, blogs and photos"

permalink:	date

paginate:	1

links:
 - name:	Home
 - url:		/
 - name:	Blog
 - url:		/
 - name:	Notes
 - url:		/
 - name:	Photos
 - url:		/
 - name:	About
 - url:		/
