name:		"6677ba's Notes"
description:	"tech notes, blogs and photos"

permalink:	date

paginate:	3

links:
 - name:	Home
   url:		/
 - name:	Blogs
   url:		/blogs.html
 - name:	Notes
   url:		/notes.html
 - name:	Photos
   url:		/photos.html
 - name:	About
   url:		/about.html

categories:
 - name:	Blogs
   url:		/blogs.html
 - name:	Notes
   url:		/notes.html
 - name:	Français
   url:		/frençais.html
 - name:	Photos
   url:		/photos.html
